# RETRY TEST: Termination message regex matching
# Job writes "TRANSIENT_ERROR" to termination log on first attempt, succeeds on second
# Expects: succeeded (proves retry mechanism worked)
# Policy: retry-transient (retries when termination message matches ".*TRANSIENT.*")
numBatches: 1
batchSize: 1
queue: e2e-test-queue-retry-transient
jobs:
  - priority: 0
    namespace: personal-anonymous
    podSpec:
      terminationGracePeriodSeconds: 0
      restartPolicy: Never
      containers:
        - name: retry-termination-msg
          imagePullPolicy: IfNotPresent
          image: alpine:3.20.0
          command:
            - sh
            - -c
            - |
              # Pod name format: armada-<jobId>-0-<runIndex>
              RUN_INDEX=$(hostname | rev | cut -d'-' -f1 | rev)
              echo "=== Retry Termination Message Test ==="
              echo "Run index: $RUN_INDEX"

              if [ "$RUN_INDEX" = "0" ]; then
                echo "First attempt: writing TRANSIENT error to termination log"
                echo "TRANSIENT_ERROR: simulated transient failure for retry test" > /dev/termination-log
                exit 1
              else
                echo "Retry attempt $RUN_INDEX: succeeding"
                exit 0
              fi
          resources:
            limits:
              memory: 25Mi
              cpu: 100m
            requests:
              memory: 25Mi
              cpu: 100m
---
timeout: "120s"
expectedEvents:
  - submitted:
  - succeeded:
