name: Release Armada components

on:
  push:
    branches:
      - v*

permissions:
  contents: write

jobs:
  compare_tags:
#    if: github.repository_owner == 'armadaproject'
    name: "Compare tags"
    runs-on: ubuntu-22.04

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: Compare tags
        id: compare_tags
        run: |
          allowed_branch="devel"
          ref=${{ github.event.workflow_run.head_branch }}
          sha=${{ github.event.workflow_run.head_sha }}
          case $ref in
            v?*)
              [ $(git rev-parse refs/tags/$ref) == $sha ] &&
              [ $(git branch --contains=$sha $allowed_branch | wc -l) -eq 1 ]
            ;;
            *)
              false
            ;;
          esac
          if [ $? -ne 0 ]; then
            echo "::error ::Invalid ref $ref $sha"
            echo "::set-output name=tag_match::false"
            exit 1
          else
            echo "Latest tag ($ref) matches the current commit ($sha)."
            echo "::set-output name=tag_match::true"
          fi

  release:
    needs: compare_tags
    if: needs.compare_tags.outputs.tag_match == 'true'
    name: "Release"
    runs-on: ubuntu-22.04
    environment: armada-dockerhub

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch Git tags
        run: git fetch --force --tags

      - name: Setup Golang with Cache
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version: "1.20"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: "Docker login"
        uses: "docker/login-action@v2"
        with:
          username: "${{ secrets.DOCKERHUB_USER }}"
          password: "${{ secrets.DOCKERHUB_PASS }}"

      - name: Set up Syft
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Set GORELEASER_PREVIOUS_TAG # Workaround, GoReleaser uses 'git-describe' to determine a previous tag.
        run: echo "GORELEASER_PREVIOUS_TAG=$(git -c 'versionsort.suffix=-rc' tag --list --sort=version:refname | grep -Eo '^v[0-9]{1,}.[0-9]{1,}.[0-9]{1,}$' | tail -n 2 | head -n 1)" >> $GITHUB_ENV

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: v1.18.2
          args: "-f ./.goreleaser.yml release --clean"
        env:
          FULL_RELEASE: true
          DOCKER_REPO: "gresearch"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          DOCKER_BUILDX_BUILDER: "${{ steps.buildx.outputs.name }}"
          DOCKER_BUILDX_CACHE_FROM: "type=gha"
          DOCKER_BUILDX_CACHE_TO: "type=gha,mode=max"

      - name: Push Docker image README.md's
        uses: ./.github/workflows/docker-readme
        with:
          docker_owner: "gresearch"
          docker_user: "${{ secrets.DOCKERHUB_USER }}"
          docker_pwd: "${{ secrets.DOCKERHUB_PASS }}"
