name: Validate Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  compare_tags:
#    if: github.repository_owner == 'armadaproject'
    name: "Compare tags"
    runs-on: ubuntu-22.04

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: Compare tags
        env:
          ALLOWED_BRANCH: "devel"
        run: |
          ref=${{ github.ref }}
          tag=${ref#refs/tags/}
          echo "Current tag: $tag"
          sha=${{ github.sha }}
          echo "Current sha: $sha"
          case $tag in
            v?*)
              echo "Valid does latest tag $tag match the current commit $sha?"
              [ $(git rev-parse refs/tags/$tag) == $sha ] &&
              [ $(git branch --contains=$sha $ALLOWED_BRANCH | wc -l) -eq 1 ]
            ;;
            *)
              echo "Invalid tag $tag"
              false
            ;;
          esac
          if [ $? -ne 0 ]; then
            echo "Latest tag ($ref) does not match the current commit ($sha)."
            echo "::error ::Invalid ref $ref $sha"
            exit 1
          else
            echo "Latest tag ($ref) matches the current commit ($sha)."
          fi
